sudo: false
language: java
jdk:
  - oraclejdk8

after_success:
- gradle artifactoryPublish

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

